### ISSUE TITLE
Bug from output

### ISSUE THREAD

**Issue by andrew36999** [Gutek8134/AID-dice-rolling#13]
First time it worked.
But now it keeps failing after the second attempt.

I used the state creator, made the scenario properly.
Then I put in `!setstate(copied info)`
Then I try out `!showStats(character)`

And then I get a

> Error continuing story: This Scenario has a bug in its Input Modifier: Cannot convert undefined or null to object
>     at Function.keys (<anonymous>)

Yes I gave the character a name and filled in the copied info & character spaces with my own info.

an hour ago it all worked and now, it's been a hour of backtracking, trying things out, completely resetting and nothing works, I don't get it.

Can you help me out?

**Comment by andrew36999** [comment]
Correction: error displayed is

Error continuing story: This Scenario has a bug in its Input Modifier: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)

**Comment by andrew36999** [comment]
Correction, error displayed from aidungeon is:
```
Error continuing story: This Scenario has a bug in its Input Modifier: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
```

**Comment by Gutek8134** [comment]
As I've stated on discord, state creator is two updates behind dice rolling, I'm working on the overhaul. Until then, you'll have to add things with other commands.

If you're really interested in what exactly doesn't work, you can send what you get from !getState
